name: daily-run

on:
  schedule:
    - cron: '0 14 * * *'   # JST 23:00
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'


      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          WORKSHEET_NAME: ${{ secrets.WORKSHEET_NAME }}
          GSA_JSON: ${{ secrets.GSA_JSON }}
          CHROME_PATH: ${{ steps.chrome.outputs.chrome-path }}
        run: |
          python main.py
