name: daily-run

on:
  schedule:
    - cron: '0 8 * * *'   # 08:00 UTC = 17:00 JST
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # main.py が Selenium を使う場合のみ
      - uses: browser-actions/setup-chrome@v1

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write service account json
        run: echo '${{ secrets.GSA_JSON }}' > service_account.json

      - name: Run main.py (update sheet)
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          WORKSHEET_NAME: ${{ secrets.WORKSHEET_NAME }}
          KEY_PATH: service_account.json
          CHROME_PATH: ${{ env.CHROME_PATH }}
          GSA_JSON: ${{ secrets.GSA_JSON }}
        run: python main.py
